// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: scheduler.proto
// Original file comments:
// Copyright 2015 gRPC authors.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_scheduler_2eproto__INCLUDED
#define GRPC_scheduler_2eproto__INCLUDED

#include "scheduler.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace com {
namespace oppo {
namespace ohacker {
namespace scheduler {

// The Scheduler service definition.
class SchedulerService final {
 public:
  static constexpr char const* service_full_name() {
    return "com.oppo.ohacker.scheduler.SchedulerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::oppo::ohacker::scheduler::ReadyResponse>> Asyncready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::oppo::ohacker::scheduler::ReadyResponse>>(AsyncreadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::oppo::ohacker::scheduler::ReadyResponse>> PrepareAsyncready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::oppo::ohacker::scheduler::ReadyResponse>>(PrepareAsyncreadyRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ready(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::oppo::ohacker::scheduler::ReadyResponse>* AsyncreadyRaw(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::oppo::ohacker::scheduler::ReadyResponse>* PrepareAsyncreadyRaw(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::oppo::ohacker::scheduler::ReadyResponse>> Asyncready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::oppo::ohacker::scheduler::ReadyResponse>>(AsyncreadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::oppo::ohacker::scheduler::ReadyResponse>> PrepareAsyncready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::oppo::ohacker::scheduler::ReadyResponse>>(PrepareAsyncreadyRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ready(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response, std::function<void(::grpc::Status)>) override;
      void ready(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::com::oppo::ohacker::scheduler::ReadyResponse>* AsyncreadyRaw(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::com::oppo::ohacker::scheduler::ReadyResponse>* PrepareAsyncreadyRaw(::grpc::ClientContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ready_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ready : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ready() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ready() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestready(::grpc::ServerContext* context, ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::grpc::ServerAsyncResponseWriter< ::com::oppo::ohacker::scheduler::ReadyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ready<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ready : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_ready() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::com::oppo::ohacker::scheduler::ReadyRequest, ::com::oppo::ohacker::scheduler::ReadyResponse>(
          [this](::grpc::ServerContext* context,
                 const ::com::oppo::ohacker::scheduler::ReadyRequest* request,
                 ::com::oppo::ohacker::scheduler::ReadyResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->ready(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_ready() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_ready<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ready : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ready() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ready() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ready : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_ready() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ready() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestready(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ready : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_ready() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->ready(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_ready() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ready(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ready : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ready() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::com::oppo::ohacker::scheduler::ReadyRequest, ::com::oppo::ohacker::scheduler::ReadyResponse>(std::bind(&WithStreamedUnaryMethod_ready<BaseClass>::Streamedready, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ready() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ready(::grpc::ServerContext* context, const ::com::oppo::ohacker::scheduler::ReadyRequest* request, ::com::oppo::ohacker::scheduler::ReadyResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedready(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::com::oppo::ohacker::scheduler::ReadyRequest,::com::oppo::ohacker::scheduler::ReadyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ready<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ready<Service > StreamedService;
};

}  // namespace scheduler
}  // namespace ohacker
}  // namespace oppo
}  // namespace com


#endif  // GRPC_scheduler_2eproto__INCLUDED
